### ISSUE TITLE
Run quickstart example failed

### ISSUE THREAD

**Issue by zxsimple** [databricks/mlflow#4]
While run `python example\quickstart\test.py` it reports error:
> Exception: Tracking URI must be a local filesystem URI of the form 'file:///...' or a remote URI of the form 'http://...'. Please update the tracking URI via mlflow.set_tracking_uri

Haven't found document about update URI setting.

**Comment by zxsimple** [comment]
After modification of the example code, it could send training data to the tracking server.
```
from mlflow import log_metric, log_param, log_artifacts, set_tracking_uri
set_tracking_uri("http://localhost:5000")
```

Please update the documentation.

**Comment by rquintino** [comment]
probably same issue, didn't notice this one was for the same error sorry, 
I was testing on windows, used local path but with file:// prefix, solved also

**_default local tracking uri not working on windows? "Tracking URI must be a local filesystem URI of the form 'file:///...' or a remote URI " #10_**
https://github.com/databricks/mlflow/issues/10

**Comment by smurching** [comment]
@zxsimple @rquintino thanks for raising this issue, we currently determine whether the tracking URI is a local filesystem URI by checking that it begins with `/` or `file://`. I'm not sure that using `file://` will work actually (are you able to see run information in the UI?), since we use URI-unaware Python APIs to write run data to disk. Will work on a fix for this :)

**Comment by rquintino** [comment]
hi @smurching  thx, yes, after doing this, UI picked the runs/experiments properly, could use it without errors

**Comment by aarondav** [comment]
Closing in favor of #10 to track the follow-up Windows-related work.
